esHost: localhost

spring:
  elasticsearch:
    connection-timeout: 30
    uris: http://${esHost}:9200
  datasource:
    url: jdbc:mysql://localhost:3306/electrical_transport?serverTimezone=GMT%2B8
    username: root
    password: zjj20001031
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
